//! Operating-mode orchestration.
//!
//! Work: comfort shift, auto fan, boost off, balanced power, notifications on.
//! Game: turbo shift, advanced fan, boost on, performance power, notifications
//! off and telemetry every 5s. If Steam exists, an optional Proton env template
//! is created; the user still controls Steam launch options.
//! Eco: eco shift, auto fan (EC-managed cooling), boost off, power-saver,
//! 80% battery health limit and notifications off. Optimized for battery
//! longevity and energy efficiency — fan stays on auto to prevent thermal
//! throttling instead of forcing silent mode.

use serde::Serialize;
use std::{fs, path::PathBuf};

use crate::{monitor::TelemetryEngine, msi_ec, optimizer};

#[derive(Serialize)]
pub struct OperatingModeResult {
    pub mode: String,
    pub warnings: Vec<String>,
}

fn attempt(warnings: &mut Vec<String>, label: &str, action: impl FnOnce() -> Result<(), String>) {
    if let Err(error) = action() {
        warnings.push(format!("{label}: {error}"));
    }
}

fn write_proton_template() -> Result<(), String> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or("HOME unavailable")?;
    let steam_found = [home.join(".steam/steam"), home.join(".local/share/Steam")]
        .iter()
        .any(|path| path.exists());
    if !steam_found {
        return Err("Steam/Proton not detected".to_owned());
    }
    let directory = home.join(".config/purrdora");
    fs::create_dir_all(&directory).map_err(|error| format!("cannot create config: {error}"))?;
    fs::write(
        directory.join("proton-game-mode.env"),
        "# Optional Steam launch environment generated by Purrdora\nPROTON_USE_WINED3D=0\n",
    )
    .map_err(|error| format!("cannot write Proton template: {error}"))?;
    Err(
        "template written to ~/.config/purrdora/proton-game-mode.env; wire it into Steam manually"
            .to_owned(),
    )
}

#[tauri::command]
pub async fn set_operating_mode(
    mode: String,
    telemetry: tauri::State<'_, TelemetryEngine>,
) -> Result<OperatingModeResult, String> {
    let _control_guard = optimizer::SYSTEM_CONTROL_LOCK
        .try_lock()
        .map_err(|_| "another system mode change is already running".to_owned())?;
    let mut warnings = Vec::new();
    let (shift, fan, boost, power, muted, polling, battery_limit) = match mode.as_str() {
        "work" => (
            "comfort",
            "auto",
            false,
            optimizer::PowerProfile::Balanced,
            false,
            1,
            None,
        ),
        "game" => (
            "turbo",
            "advanced",
            true,
            optimizer::PowerProfile::Performance,
            true,
            5,
            Some(false),
        ),
        "eco" => (
            "eco",
            "auto",
            false,
            optimizer::PowerProfile::PowerSaver,
            true,
            2,
            Some(true),
        ),
        _ => return Err(format!("Unsupported operating mode: {mode}")),
    };

    attempt(&mut warnings, "Shift mode", || {
        msi_ec::set_msi_ec_shift_mode(shift.to_owned()).map(|_| ())
    });
    attempt(&mut warnings, "Fan mode", || {
        msi_ec::set_msi_ec_fan_mode(fan.to_owned()).map(|_| ())
    });
    attempt(&mut warnings, "Cooler Boost", || {
        msi_ec::set_msi_ec_cooler_boost(boost).map(|_| ())
    });
    if let Err(error) = optimizer::set_power_profile_value(power, &telemetry).await {
        warnings.push(format!("Power profile: {error}"));
    }
    attempt(&mut warnings, "Notifications", || {
        optimizer::set_notifications_muted(muted)
    });
    if let Some(enabled) = battery_limit {
        attempt(&mut warnings, "Battery limiter", || {
            crate::monitor::set_battery_limiter(enabled).map(|_| ())
        });
    }
    if mode == "game" {
        attempt(&mut warnings, "Proton optimization", write_proton_template);
        warnings.push(
            "Kernel page cache was left intact to avoid a disruptive privileged operation"
                .to_owned(),
        );
    }
    telemetry.set_polling_interval(polling);

    Ok(OperatingModeResult { mode, warnings })
}
